version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2021.10
    working_directory: ~/ProductCatalog

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # ðŸ”¥ Install Java 8 manually and switch to it
      - run:
          name: Install Java 8
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-8-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
            java -version

      - restore_cache:
          key: jars-v4-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Build project
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-v4-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Run Unit Tests
          command: ./gradlew test

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks/

      - store_test_results:
          path: app/build/test-results
